### ISSUE TITLE
Error in fuzzy_join.R

### ISSUE THREAD

**Issue by pkq** [dgrtwo/fuzzyjoin#1]
First, thanks for putting this package together. I've been trying for quite some time to wrap my head around how to accomplish exactly this task.

Unfortunately, when I try running any of the examples, I get an error message:

`Error in sapply(x_indices_l, length) * sapply(y_indices_l, length) : 
  non-numeric argument to binary operator`

I'm not familiar enough with base R to know how to fix the problem, but fortunately, it looks like someone else is: b0cfdd971302bd1dc11b804de8cf860c677bfa52. What's the proper way to request integrating this fix into your repository? Is it appropriate to create a pull request based on someone else's code?

**Comment by dgrtwo** [comment]
Thanks for commenting! I can't reproduce this error (could you share your `sessionInfo()`, but as a start I tried removed that num_each line, which is unnecessary. Can you try re-installing and running the example again?

**Comment by pkq** [comment]
Thanks for the prompt response. When I re-install and run the `stringdist_join` example, I get `Error: data_frames can only contain 1d atomic vectors and lists`. When I install the [forked version](https://github.com/strongh/fuzzyjoin), the example runs without error. Session info is:

    R version 3.2.4 (2016-03-10)
    Platform: x86_64-apple-darwin14.5.0 (64-bit)
    Running under: OS X 10.10.5 (Yosemite)

    locale:
    [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] ggplot2_2.1.0 fuzzyjoin_0.1 dplyr_0.4.3  

    loaded via a namespace (and not attached):
     [1] stringdist_0.9.4.1 Rcpp_0.12.3        tidyr_0.4.1        assertthat_0.1     grid_3.2.4        
     [6] R6_2.1.2           plyr_1.8.3         gtable_0.2.0       DBI_0.3.1          magrittr_1.5      
    [11] scales_0.4.0       lazyeval_0.1.10    tools_3.2.4        munsell_0.4.3      parallel_3.2.4    
    [16] colorspace_1.2-6

**Comment by pkq** [comment]
Works! Thanks again for the package, and for troubleshooting this so quickly!

**Comment by dgrtwo** [comment]
Happy to help!

It looks like this was an issue with the newest version of tidyr (specifically its change to the `unnest` function).

Note that while the forked version didn't give errors, it also won't take advantage of redundancy in the x and y columns. The `fuzzy_join` function is designed to perform only m x n comparisons where m is the number of _unique_ items in one column and n the uniques in the other. (e.g. in the stringdist example, it performs only 5 x 5 = 25 comparisons, even though the diamonds dataset is large).

**Comment by pkq** [comment]
Whoah, that's slick!
