### ISSUE TITLE
Feature request: report distances from stringdist_join() and friends

### ISSUE THREAD

**Issue by lmullen** [dgrtwo/fuzzyjoin#10]
For the types of fuzzy joins that have some kind of a distance metric (e.g., a string distance for stringdist_join() and friends), would it be possible to have an option to return the distance measure as a new column in the resulting data frame?

**Comment by dgrtwo** [comment]
Good idea!

**Comment by dgrtwo** [comment]
Added `distance_col` option to those functions (and ability for `match_fun` in `fuzzy_join` to return multiple columns generally). Let me know how it works out!

**Comment by lmullen** [comment]
Works brilliantly on some test data. I'll give it a shot with the real data. Thanks so much!
