### ISSUE TITLE
error when one dataframe only has one column

### ISSUE THREAD

**Issue by mgacc0** [dgrtwo/fuzzyjoin#13]
When trying to join two dataframes, if one of the dataframes has only one column an error happens:

`stringdist_inner_join(df1, df2)`
`Error: cannot convert object to a data frame`

Maybe it's dropping one dimension (from dataframe with one column to vector)?

**Comment by mgacc0** [comment]
fixed the title

**Comment by dgrtwo** [comment]
I cannot reproduce. For example the following works:

    library(dplyr)
    library(fuzzyjoin)
    d1 <- data_frame(a = c("apple", "banana"))
    d2 <- data_frame(b = c("appl", "banan"))
    stringdist_inner_join(d1, d2, by = c("a" = "b"))

Could you provide a reproducible example, as well as the output of `sessionInfo()`?

**Comment by mgacc0** [comment]
Of course:
```r
  df1 <- structure(list(
    nome = c("AZUCENA MONTOYA ROMERO", "TRINIDAD BORJA BORJA")),
    .Names = c("nome"), row.names = 94:95, class = "data.frame") 
  
  df2 <- structure(list(NOME2 = c("AZUCENA MONTOYA ROMERO", "SHEILA REFOJO FURELOS"),
                        EXPEDIENTE = c("15030/2450/12", "15030/2456/12")),
                   .Names = c("NOME2", "EXPEDIENTE"), row.names = 1163:1165, class = "data.frame")
  stringdist_inner_join(df1, df2, by=c("nome"="NOME2"), max_dist=2)
```

Thanks in advance :)

**Comment by dgrtwo** [comment]
Fixed, thanks!
