### ISSUE TITLE
unit of max_dist in geo_join?

### ISSUE THREAD

**Issue by masalmon** [dgrtwo/fuzzyjoin#15]
I wonder if there is a small mistake in the documentation of `geo_join`:

By default `geosphere::distGeo` outputs distances in meters, and other `geosphere` functions probably do. 

So if the `unit` given to `geo_join` is not miles, the distance is calculated in meters I guess? But in the documentation the other possible value for `unit` is "km" so I'm confused.

**Comment by dgrtwo** [comment]
We divide by 1000 in [this line](https://github.com/dgrtwo/fuzzyjoin/blob/master/R/geo_join.R#L112)- does that resolve the issue? 😃 

I chose to return km rather than meters since I knew I preferred to have miles rather than feet, and km is on a similar scale.

**Comment by masalmon** [comment]
Oh no I had missed that line, sorry!  And I think km are better than m, good job!
