### ISSUE TITLE
Package for extending the genome_join methods

### ISSUE THREAD

**Issue by const-ae** [dgrtwo/fuzzyjoin#27]
Hi,

first let me say, that I really like your package, especially the `genome_join` functions, which save me a lot of conversions between data frames and `GenomicRanges`. 

But a few methods for dealing with genomic intervals were missing so I wrote a package ([tidygenomics](https://github.com/Artjom-Metro/tidygenomics)) to fill those gaps.

Because I am using your genome_join implementation and mimic your nomenclature, I wanted to ask if this is okay for you? And secondly, so far only the fuzzyjoin version on github supports genome_join, do you have plans to release this to CRAN?

Best Regards,
Constantin

**Comment by dgrtwo** [comment]
I love this!

Yes, fuzzyjoin is high on my priority list for CRAN release. Let me see if it I can get it done early next week.

**Comment by Artjom-Metro** [comment]
Great, I am happy to hear that :)

**Comment by tsibley** [comment]
👍 I too would appreciate seeing a CRAN release of the current dev version, with `genome_join`.

**Comment by const-ae** [comment]
Thanks for updating the CRAN version, I have now also [published](https://cran.r-project.org/package=tidygenomics) my package :) 🎉🎉
