### ISSUE TITLE
BUG: fuzzy_join's return errors when joining multiple times to the same column

### ISSUE THREAD

**Issue by twolodzko** [dgrtwo/fuzzyjoin#28]
The error occurred in situation as exemplified below:

```
> fuzzy_left_join(mtcars, mtcars,
+                 by = c("gear" = "cyl", "carb" = "cyl"),
+                 match_fun = list(`==`, `==`))
Error: Length of match_fun not equal to columns specified in 'by'.
```

First, the error message is misleading because lengths do not mach _because_ fuzzyjoin made them so to make the comparisons. Second, it should not occur at all since this is not a bug but users behavior that is should be perfectly valid (expecting each column to be used only once does not seem reasonable). Moreover, this behavior is inconsistent as the following code does not produce errors:

```
fuzzy_left_join(mtcars, mtcars,
                by = c("cyl" = "gear", "cyl" = "carb"),
                match_fun = list(`==`, `==`))
```

The practical use case is when one wants to do left joins like `x.start < y.date & y.date < x.end` as equivalent to SQL's: `SELECT  * FROM table1 x LEFT  JOIN table2 y ON y.value BETWEEN x.start AND x.end`

**Comment by dgrtwo** [comment]
Thanks! This bug should be fixed now.
