### ISSUE TITLE
Issue in autocomplete for developers's version 

### ISSUE THREAD

**Issue by GuiMarthe** [dgrtwo/fuzzyjoin#31]
When I installed the github version, I kept getting the following error when pressing tab, and when loading the package for the first time:

    Error in fetch(key) : 
      lazy-load database '~/R/x86_64-pc-linux-gnu-library/3.4/fuzzyjoin/help/fuzzyjoin.rdb' is corrupt

**Comment by dgrtwo** [comment]
This usually isn't related to a particular package or solvable  (I get it sometimes for all kinds of packages, especially within RStudio). Please try restarting R, or possibly installing again.
