### ISSUE TITLE
geo_join

### ISSUE THREAD

**Issue by masalmon** [dgrtwo/fuzzyjoin#4]
I'm going to try and add two-by-two comparison: right now we'd like to join tables based on geographical distance for which you use two columns in each dataframe.

**Comment by dgrtwo** [comment]
This has been implemented in 6a152c92781156f929e49689d0a794814410b81b (the message mistakenly says it closes issue 2).

Thanks for the idea!

**Comment by masalmon** [comment]
Ah that's awesome!

**Comment by masalmon** [comment]
The readme does not mention it yet. ;-)
