### ISSUE TITLE
regex_semi_join doesn't pass back in joined variables

### ISSUE THREAD

**Issue by azadag** [dgrtwo/fuzzyjoin#42]
the semi-join appears to work, but doesn't add joined variables
Working from an example I had saved from twitter a while back.
```
library(tidyverse)
library(fuzzyjoin)
regexes <- read_csv(
"regex, type
Windows, Windows-ish
Red Hat|CentOS|Fedora, Fedora-ish
Ubuntu|Debian,Debian-ish
CoreOS|Amazon,Amazon-ish")

os <- read_lines("https://rud.is/dl/os.txt", na = "NA")
os <- as.data.frame(os, na.rm = TRUE)
os <- os[complete.cases(os),]
os <- as.data.frame(os, na.rm = TRUE)

os_left <- os %>% 
replace_na(list(regex = "Unknown")) %>% 
  regex_left_join(regexes, c(os = "regex")) 

os_semi <- os %>% 
replace_na(list(regex = "Unknown")) %>% 
  regex_left_join(regexes, c(os = "regex")) 
```

os2 returns a dataframe with 3 variables
os3 returns one variable (factor)

**Comment by azadag** [comment]
Sorry. This appears to have been a dplyr issue? I updated to .7.5 from .7.4 and it cleared up.

**Comment by dgrtwo** [comment]
Late notice, but this was indeed a bug in how fuzzyjoin handled one-column data.frames! Likely took a while to notice because most users use tbl_dfs.

Now fixed, thanks a lot for this report!

**Comment by azadag** [comment]
!!! great!
