### ISSUE TITLE
stringdist_left_join: Why doesn't an unspecified max_dist yield a tibble with x * y rows?

### ISSUE THREAD

**Issue by jzadra** [dgrtwo/fuzzyjoin#44]
I"m a bit unclear on why `stringdist_left_join` doesn't yield a tibble with x * y rows if `max_dist` is left unspecified. 

Any word can be modified to any other word by replacing every letter, therefore shouldn't a row be returned for every combination of x and y?  

I realize that this would essentially be producing the same result as `stringdist::stringdistmatrix()`, and it isn't actually a result I"m looking for, but it just seems as though `stringdist_left_join` has a hidden `max_dist` cutoff, and I"m curious if that's the case what it is or how it's determined.

Thanks!

**Comment by dgrtwo** [comment]
There is a default value of `max_dist` of 2. It's not hidden, it's the default argument to the function:

![image](https://user-images.githubusercontent.com/994718/43536147-dd8532fc-9589-11e8-88a3-3ca9b76bb5bc.png)

It's likely most users will want to set a specific value for `max_dist` based on their particular application. But the reason for choosing a non-infinite default is that it's more likely that someone who doesn't take time to specify wants "strings that are close, like a typo or two away" than "any pairing of strings".

Does that make sense?

**Comment by jzadra** [comment]
I'm a moron.    I was just on my way back to delete this as I had just figured it out.  I've been banging my head against a difficult name matching problem for too long. Thanks David.

**Comment by dgrtwo** [comment]
Oh, no worries at all!
