### ISSUE TITLE
difference_right_join does not create distance_col when there are no overlapping rows

### ISSUE THREAD

**Issue by dewoller** [dgrtwo/fuzzyjoin#57]
_difference_right_join_ (and probably others) do not create the designated _distance_col_ when there are no overlapping rows.  This makes use of these functions in a general pipeline problematic because the column you expect to exist does not.  Example below

``` r

library(fuzzyjoin)
a <- data.frame(replicate(2,sample(20:30,10,rep=TRUE))) 

b <- data.frame(replicate(2,sample(1:10,10,rep=TRUE))) 

difference_right_join( a, b, by='X1', max_dist = 1, distance_col='distance')
#>    X1.x X2.x X1.y X2.y
#> 1    NA   NA   10    4
#> 2    NA   NA    7    5
#> 3    NA   NA    9    2
#> 4    NA   NA    1   10
#> 5    NA   NA    8    4
#> 6    NA   NA    5    1
#> 7    NA   NA    4    9
#> 8    NA   NA    1    3
#> 9    NA   NA    9    5
#> 10   NA   NA    3    6
```

<sup>Created on 2019-08-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dgrtwo** [comment]
Thanks for this find, this is now fixed and relevant unit tests added! Please try it out and let me know if it doesn't fit your expectations.

I expect this to be submitted to CRAN sometime this week.
