### ISSUE TITLE
stringdist_semi_join does not join tables

### ISSUE THREAD

**Issue by marboe123** [dgrtwo/fuzzyjoin#66]
It seems to me that stringdist_semi_join only provides the rows from table x which have a match in table y, although it does not join with the rows from y. (it only identifies which rows in x have a match in y).

**Comment by dgrtwo** [comment]
That’s the intended behavior. `stringdist_semi_join` is analogous to `semi_join` from dplyr. [See here for more on the six types of join!](https://dplyr.tidyverse.org/articles/two-table.html) 🤗

You might be looking for `stringdist_inner_join`, or `stringdist_left_join`?

**Comment by marboe123** [comment]
Thank you for your quick reply! Good to know it is intended behavior.
Unfortunately stringdist_inner_join and stringdist_left_join do not solve my problem. I have posted my problem on stackoverflow. Maybe you can take a quick look? That would be great!

https://stackoverflow.com/questions/61145788/stringdist-semi-join-only-shows-columns-from-dataframe1
