### ISSUE TITLE
clarify license

### ISSUE THREAD

**Issue by kleinschmidt** [dgrtwo/fuzzyjoin#80]
From the CRAN entry it looks like this is licensed under MIT, but the LICENSE file here just has the copyright information.  Could you clarify that this code is MIT licensed and if so, include the appropriate LICENSE file?

**Comment by dgrtwo** [comment]
It is licensed under MIT. The R package standard for licensing is that licenses are specified with a [line in the DESCRIPTION](https://github.com/dgrtwo/fuzzyjoin/blob/master/DESCRIPTION#L14) (`License: MIT + file LICENSE`) and a template (for MIT it gets slotted in here: https://www.r-project.org/Licenses/MIT).

See here for more! https://cran.rstudio.com/doc/manuals/r-devel/R-exts.html#Licensing
